### ISSUE TITLE
Training a calss-conditional model

### ISSUE THREAD

**Issue by payam-dig** [justinlovelace/latent-diffusion-for-language#6]
Hi there, First I want to thank you for publicly providing this repo. It works great! I have been able to train a model using my own text data. The way I did it was I mimicked the format of the roc input data and trained the model using the roc script. However, I wonder if I can extend my work to training a class conditional model. Based on your paper, I know that you have done that for the SST and AG_news data, but the sample data for those are not provided so that I can get an idea about how it can be done. It'd be great if you could give me an idea about how it can be done, for example, for the roc data. Any kind of guidance will be appreciated.

**Comment by Vikramank** [comment]
Hi @payam-dig , 
Where you able to run generation script for ROC dataset? since its unconditional, the num_classes is zero and this creates an issue while running the "gen_text_diffusion.sh" file

**Comment by payam-dig** [comment]
Hi there,

Yes, I was able to run the script. Also, I figured that the 0 causes an issue when I want to generate sentences, so I made it 1 to get around the issue,

Payam

**Comment by justinlovelace** [comment]
Thanks for the interest! 

For the class conditional models, we utilize datasets available on the Huggingface Hub and load them directly from there. To train a class-conditional model on your own dataset, you would just need to add the appropriate processing code to `dataset_utils/text_dataset.py` to extract the text and class labels from your dataset files. You would also need to add the relevant information (e.g. number of classes) about the new dataset to `CONSTANTS.py`. 

We used the `gen_text_diffusion.sh` script to generate the synthetic classification datasets (used for Table 4 in the paper), so it only supports class-conditional models. Our primary evaluation for both unconditional and class-conditional diffusion models is done using the `scripts/diffusion/eval_text_diffusion.sh` script as instructed in the README which also saves the generations to a text file.

You could also extend the `gen_synthetic_dataset()` function to handle unconditional models as has been discussed above so that you can use the `gen_text_diffusion.sh` script for unconditional generation. 

If you have any additional questions, then feel free to re-open the issue!

**Comment by payam-dig** [comment]
Thank you for the detailed instructions, Justin!

Payam

**Comment by Vikramank** [comment]
hi @payam-dig ,
Could you please elaborate where you made the changes? I changed the num_classes to 1, but still no luck. I'm getting the following error : 
`RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 0`

**Comment by Vikramank** [comment]
hi @justinlovelace , 
Thanks for the information. However, when I tried running `scripts/diffusion/eval_text_diffusion.sh` pointing to the roc saved model. However, I'm getting the same error: 
`RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 0`. 
Also, I noticed that the model size(`model.pt` file) of unconditional model is much higher (~3GB) compared to the the conditional model (~100MB). @payam-dig  did you also encounter the same?

**Comment by payam-dig** [comment]
Hi @Vikramank 
The 0 value for num_classes in train_text_diffusion.py resulted in division by 0. So, I made it 1 as a temporary remedy.
I've never created a conditional model, so I can't comment on that, but I can confirm that my unconditional models are also a few GBs.

**Comment by Vikramank** [comment]
hi @payam-dig ,
Thank you very much for the info! Just to confirm, you had set `num_classes = self.diffusion.diffusion_model.num_classes` to 1 in line number #529 under `gen_synthetic_dataset` in denoising_diffusion.py script right? I tried that, it helps to evade the assertion error in the following error, but I'm still getting the same error that I posted above. Could you please share what other changes you had made to generate samples trained on a custom dataset?

**Comment by payam-dig** [comment]
@Vikramank 
What I changed was the following line:

num_classes = (CONSTANTS.NUM_CLASSES[args.dataset_name] if args.class_conditional else 1)

in train_text_diffusion.py (the orginal value after "else" was 0.
I see it as line 26 in that py script.

**Comment by Vikramank** [comment]
@payam-dig 
Thank you very much! it works like a charm! 
cc @justinlovelace

**Comment by payam-dig** [comment]
I'm glad it worked :)
